import { createElement } from 'lwc';
import Lwc_0307_eg5_publicvar from 'c/lwc_0307_eg5_publicvar';

describe('c-lwc-0307-eg5-publicvar', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-0307-eg5-publicvar', {
            is: Lwc_0307_eg5_publicvar
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});