import { createElement } from 'lwc';
import Lwv_0307_eg1_input from 'c/lwv_0307_eg1_input';

describe('c-lwv-0307-eg1-input', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwv-0307-eg1-input', {
            is: Lwv_0307_eg1_input
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});